### ISSUE TITLE
Ability to clear released buttons explicitly.

### ISSUE THREAD

**Issue by JAForbes** [likethemammal/gamepad-micro#3]
Would you accept a pull request for a function that clears the released buttons from the gamepad object?

The gamepad object is so conveniently structured that it is helpful to use it as the actual games storage of that data.  But this leads to stale data for `released`.

Currently the `released` property can be true for an infinite amount of frames even though the button has long been released.  It will only be updated when a new event occurs.

It'd be helpful if there was a function we could call like `gp.clear()` that gives the library permission to clear all `released` values and buttons.  That way the developer can let you know they have processed the user input and you don't need to wait for the next action.

This could be done on a per game/application basis.  But seeing as this library is already pretty high level, I hoped it could be implemented directly.

It also may be more performant to do so in the library as there is more information about what buttons need to be cleared, and this could remove the need to loop over the structure.

(Great library btw!)

**Comment by likethemammal** [comment]
Thanks!

And yea, I like that idea. I can definitely see the use for clearing the queue. Go ahead and write a pull request, then I'll look it over. Lmk if you can't figure it out or have trouble. Otherwise, I'll jump on it eventually.

**Comment by JAForbes** [comment]
@likethemammal Excellent!  I'll take a look in the near future, possibly this weekend.
